[component]
structures = [ "content_blocks" ]
label = "Newsletter Form"
description = "Generic newsletter form"
icon = "wysiwyg"
tags = ["Text"]

[props]
newsletter_title = "Join our mailing list"
newsletter_description = "Get inspiration, updates and, cool stuff!" # Add descriptions to the form.
newsletter_identifier = "correlaid.us12.list-manage.com/subscribe?u=b294bf2834adf5d89bdd2dd5a&id=915f3f3eff" # Add your MailChimp form identifier.
newsletter_button = "Subscribe"