[component]
structures = [ "content_blocks" ]
label = "Newsletter Form"
description = "Generic newsletter form"
icon = "wysiwyg"
tags = ["Text"]

[props]
newsletter_title = "Join our mailing list"
newsletter_description = "Do you want to change the world together with us?" # Add descriptions to the form.
newsletter_identifier = "" # Add sign-up form URL
newsletter_button = "Subscribe"